
CREATE TABLE rewards (
	active bool NOT NULL,
	points_cost int4 NOT NULL,
	created_at timestamp(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description text NULL,
	image_path varchar(255) NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT rewards_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
	active bool NOT NULL,
	"language" varchar(2) NULL,
	total_points int4 NOT NULL,
	created_at timestamp(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	theme varchar(10) NULL,
	avatar_type varchar(20) NULL,
	avatar_icon_name varchar(50) NULL,
	first_name varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"role" varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	avatar_data bytea NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'PARENT'::character varying, 'CHILD'::character varying])::text[]))),
	CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE behaviors (
	active bool NOT NULL,
	points int4 NOT NULL,
	created_at timestamp(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NULL,
	guideline text NOT NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT behaviors_pkey PRIMARY KEY (id),
	CONSTRAINT fkey_users_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE point_transactions (
	points int4 NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	reference_id int8 NULL,
	user_id int8 NOT NULL,
	description text NULL,
	remarks text NULL,
	"type" varchar(255) NOT NULL,
	CONSTRAINT point_transactions_pkey PRIMARY KEY (id),
	CONSTRAINT point_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['TASK'::character varying, 'REWARD'::character varying, 'BEHAVIOR'::character varying, 'PENALTY'::character varying, 'BONUS'::character varying])::text[]))),
	CONSTRAINT fkey_users_created_by FOREIGN KEY (created_by) REFERENCES users(id),
	CONSTRAINT fkey_users_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE reward_redemptions (
	points_spent int4 NOT NULL,
	approved_at timestamp(6) NULL,
	approved_by int8 NULL,
	delivered_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	requested_at timestamp(6) NOT NULL,
	reward_id int8 NOT NULL,
	user_id int8 NOT NULL,
	notes text NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT reward_redemptions_pkey PRIMARY KEY (id),
	CONSTRAINT reward_redemptions_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT fkey_rewards_reward_id FOREIGN KEY (reward_id) REFERENCES rewards(id),
	CONSTRAINT fkey_users_user_id FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT fkey_users_approved_by FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE tasks (
	awarded_points int4 NULL,
	base_points int4 NOT NULL,
	due_date date NULL,
	is_template bool NULL,
	approved_at timestamp(6) NULL,
	approved_by int8 NULL,
	assigned_user_id int8 NULL,
	completed_at timestamp(6) NULL,
	created_at timestamp(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	template_id int8 NULL,
	description text NULL,
	parent_notes text NULL,
	recurrence_type varchar(255) NOT NULL,
	status varchar(255) NOT NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT tasks_pkey PRIMARY KEY (id),
	CONSTRAINT tasks_recurrence_type_check CHECK (((recurrence_type)::text = ANY ((ARRAY['ONCE'::character varying, 'DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying])::text[]))),
	CONSTRAINT tasks_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'CHILD_COMPLETED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
	CONSTRAINT fkey_tasks_template_id FOREIGN KEY (template_id) REFERENCES tasks(id),
	CONSTRAINT fkey_users_assigned_user_id FOREIGN KEY (assigned_user_id) REFERENCES users(id),
	CONSTRAINT fkey_users_approved_by FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE behavior_evaluations (
	"committed" bool NOT NULL,
	current_points int4 NOT NULL,
	behavior_id int8 NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NOT NULL,
	week_start_date timestamp(6) NOT NULL,
	remarks text NULL,
	CONSTRAINT behavior_evaluations_pkey PRIMARY KEY (id),
	CONSTRAINT fkey_users_user_id FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT fkey_users_created_by FOREIGN KEY (created_by) REFERENCES users(id),
	CONSTRAINT fkey_behaviors_behavior_id FOREIGN KEY (behavior_id) REFERENCES behaviors(id)
);