-- V3: Create notifications table for user notifications
CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    type varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    message text NOT NULL,
    reference_id bigint,
    created_at timestamp(6) NOT NULL,
    read_at timestamp(6),
    CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Index für Performance bei Abfragen nach User
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);
CREATE INDEX idx_notifications_read_at ON notifications(read_at);