-- V7: Refactor tasks to task_definitions and task_instances

-- Create task_definitions table
CREATE TABLE task_definitions (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    description text,
    base_points int4 NOT NULL,
    recurrence_type varchar(255) NOT NULL,
    start_date date,
    end_date date,
    weekly_days text,
    created_by int8 NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT fk_task_definitions_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Create task_definition_assigned_users table (many-to-many)
CREATE TABLE task_definition_assigned_users (
    task_definition_id int8 NOT NULL,
    user_id int8 NOT NULL,
    PRIMARY KEY (task_definition_id, user_id),
    CONSTRAINT fk_task_def_assigned_users_def FOREIGN KEY (task_definition_id) REFERENCES task_definitions(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_def_assigned_users_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create task_instances table
CREATE TABLE task_instances (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_definition_id int8 NOT NULL,
    assigned_user_id int8 NOT NULL,
    due_date date NOT NULL,
    status varchar(255) NOT NULL,
    completed_at timestamp(6),
    approved_at timestamp(6),
    awarded_points int4,
    approved_by int8,
    parent_notes text,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT fk_task_instances_definition FOREIGN KEY (task_definition_id) REFERENCES task_definitions(id),
    CONSTRAINT fk_task_instances_assigned_user FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    CONSTRAINT fk_task_instances_approved_by FOREIGN KEY (approved_by) REFERENCES users(id)
);

-- Optional: Migrate existing data (this is a simple migration, adjust as needed)
-- INSERT INTO task_definitions (title, description, base_points, recurrence_type, created_by, created_at)
-- SELECT title, description, base_points, recurrence_type, 1, created_at FROM tasks WHERE is_template = true OR is_template IS NULL;

-- For instances:
-- INSERT INTO task_instances (task_definition_id, assigned_user_id, due_date, status, completed_at, approved_at, awarded_points, approved_by, parent_notes, created_at)
-- SELECT template_id, assigned_user_id, due_date, status, completed_at, approved_at, awarded_points, approved_by, parent_notes, created_at FROM tasks WHERE template_id IS NOT NULL;