package org.openfamilycompass.controller;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ModelAttribute;

/**
 * Global controller advice to provide version information to all views.
 * Version information is injected from git.properties (generated by
 * git-commit-id-plugin)
 * and application.yml
 */
@ControllerAdvice
public class VersionController {

    @Value("${git.branch:unknown}")
    private String gitBranch;

    @Value("${git.commit.id.abbrev:unknown}")
    private String gitCommitIdAbbrev;

    @Value("${git.describe:unknown}")
    private String gitDescribe;

    @Value("${git.build.version:1.0.0-SNAPSHOT}")
    private String buildVersion;

    @Value("${project.version:1.0.0-SNAPSHOT}")
    private String projectVersion;

    /**
     * Provides version information to all views.
     * If running a release (e.g., v1.0.0-alpha), gitDescribe will show the tag.
     * Otherwise, shows the commit hash for development builds.
     */
    @ModelAttribute("appVersion")
    public String getAppVersion() {
        // Try to get version from git describe (e.g., "v1.0.0-alpha" for releases)
        if (!gitDescribe.equals("unknown") && !gitDescribe.isEmpty()) {
            return gitDescribe.replaceFirst("^v", ""); // Remove 'v' prefix if present
        }

        // Fallback to commit hash for development builds
        if (!gitCommitIdAbbrev.equals("unknown") && !gitCommitIdAbbrev.isEmpty()) {
            return gitCommitIdAbbrev;
        }

        // Last resort: use project version
        return projectVersion;
    }

    /**
     * Provides build information to views for debugging.
     */
    @ModelAttribute("appBuildInfo")
    public String getAppBuildInfo() {
        StringBuilder info = new StringBuilder();

        // Branch info
        if (!gitBranch.equals("unknown") && !gitBranch.isEmpty()) {
            info.append(gitBranch);
        }

        // Commit hash
        if (!gitCommitIdAbbrev.equals("unknown") && !gitCommitIdAbbrev.isEmpty()) {
            if (info.length() > 0) {
                info.append(" / ");
            }
            info.append(gitCommitIdAbbrev);
        }

        return info.length() > 0 ? info.toString() : "Development";
    }
}
